name: Java CI # Name of the workflow

on: [push] # When to run the workflow

jobs:
  build:

    runs-on: ubuntu-latest # Operating system to run on

    steps:

      - uses: actions/checkout@v4 # Step 1: get the code from our repo

      - name: Set up JDK # Step 2: install java developer kit
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven # Step 3: build project using Maven
        run: mvn -B package --file pom.xml